### ISSUE TITLE
Create plugin of encrypt and decrypt

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [YasunoriMATSUOKA/crypt-asset-tool#32]
## Problems

- When API key and API Secret is saved in localStorage, they must be encrypted.

## Overview

- Firstly, create encrypt and decrypt methods in plugins directory.
- Spec
  - AES256
  - CBC mode
  - Initial Vector
  - Salt
- Reference
https://qiita.com/hm0429/items/2acee723170b32b91304

## Tasks

- [ ] Create plugins/crypto.js
  - [ ] encrypt
  - [ ] decrypt
- [ ] Modify nuxt.config.js
- [ ] Modify components/ApiConfig.vue
