### ISSUE TITLE
Create plugin of master private key and public key

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [YasunoriMATSUOKA/crypt-asset-tool#33]
## Problem

At least one private key is need to encrypt something.
It must be complicated to prevent to guess.

## Overview

Use crypto module or nem-library or symbol-sdk to generate random key pair.
Spec must be discussed.

## Tasks

- [ ] Create bellow plugins, compare them and decide which should be used.
  - [ ] Use crypto module case
  - [ ] Use nem-library case
  - [ ] Use symbol-sdk case
